# An example for what Rocket.toml should be
[debug.databases]
db = { url = "postgres://username:password@localhost/db" }

[testing.databases]
db = { url = "postgres://username:password@localhost/dbTesting" }
