# An example for what Rocket.toml should be
[global.databases]
db = { url = "postgres://username:password@localhost/db" }

# Second url for connecting to the testing DB
# db = { url = "postgres://username:password@localhost/db" }
