version: 2.1

orbs: 
  heroku: circleci/heroku@1.2.6

commands:
  configure-db:
    steps:
      - run: cargo install diesel_cli --no-default-features --features postgres || true
      - run: diesel migration run --database-url postgres://testuser:testpassword@localhost/sysc4806Testing

  setup:
    steps:
          - checkout
          - restore_cache:
              key: '{{ checksum "Cargo.lock" }}'
          - configure-db
          - run: rustup toolchain install nightly
          - run: cargo +nightly build
          - save_cache:
              key: '{{ checksum "Cargo.lock" }}'
              paths:
                - target/debug/build
                - ~/.cargo/bin
                

  test:
    steps:
      - run: cargo +nightly test

executors:
  rust-docker:
    docker:
      - image: cimg/rust:1.59.0
        environment:
          PGHOST: 127.0.0.1
          PGUSER: root
          ROCKET_PROFILE: testing
          ROCKET_DATABASES: '{db = { url = "postgres://testuser:testpassword@localhost/sysc4806Testing" }}'

      - image: cimg/postgres:14.0
        environment:
          POSTGRES_USER: testuser
          POSTGRESS_PASSWORD: testpassword
          POSTGRES_DB: sysc4806Testing

jobs:
  rust-test:
    executor: rust-docker
    steps:
      - setup
      - test

format:
  parameters:
    with-cache: true

workflows:
  rust-testing:
    jobs: 
      - rust-test
      - heroku/deploy-via-git:
          context:
            - testing
          force: true
          requires:
            - rust-test
          filters:
            branches:
              only:
                - master
